# Generated by Django 5.2 on 2025-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.FloatField(verbose_name='Price')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('category', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Accesories'), (3, 'Wireless Gadgets'), (4, 'Laptops'), (5, 'Television'), (6, 'Fridges'), (7, 'Coolers'), (8, 'Cameras and Accessiories')], verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='IS_Available')),
                ('pimage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
