# Generated by Django 5.2 on 2025-05-13 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_app', '0002_alter_product_category_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('fullname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
